feat: add support for customer argocd api server name
argoproj-labs/terraform-provider-argocd pull request #405
Opened 2024-07-05 06:11 UTC by MarshallOfSound

Fixes #231 as the API client now supports passing custom server names.

Honestly quite new to TF providers so not 100% sure how to test this, but codewise it's pretty straight forward wiring afaics.

2024-07-05 07:37 UTC, the-technat approved these changes
LGTM (as far as my provider knowledge goes)

Regarding the failed build, could you run `make generate` locally?

2024-07-05 09:04 UTC, MarshallOfSound commented
> Regarding the failed build, could you run make generate locally?

Yup 👍 Looks like I struggle with alphabetical ordering 😆

2024-07-19 14:14 UTC, onematchfox commented
...

2024-08-04 20:16 UTC, onematchfox commented
...

2024-08-08 14:31 UTC, onematchfox requested changes

2024-08-08 14:31 UTC, onematchfox commented on argocd/provider.go
> +		ServerName:               getStringFromResourceData(d, "server_name"),
``` suggestion
```

I'm afraid this is not going to have the desired behaviour. What you want to be doing is setting it [here](https://github.com/argoproj-labs/terraform-provider-argocd/blob/dfa0f72848fc1bb90f6ffe8cc9f943dd0f7c92e6/internal/provider/model_provider.go#L239) instead. 

Something like the following should do the trick:
```go
opts.ServerName = getDefaultString(p.ServerName, "ARGOCD_SERVER_NAME")

if opts.ServerName == "" {
	opts.ServerName = "argocd-server"
}
```

2024-08-08 14:31 UTC, onematchfox commented on argocd/provider.go
> +				Description: "The Argo CD API Server name (default \"argocd-server\")",
``` suggestion
				Description: "The name of the Argo CD Server component as specified by the value of the `label` `app.kubernetes.io/name`. Only applicable when port forwarding. Can be set through the `ARGOCD_SERVER_NAME` environment variable. Defaults to `argocd-server`.",
```

Reminder, you'll need to regenerate the docs after committing this change.

2024-09-02 12:53 UTC, closed without merging