Fix: Extend policy validation to support update and delete actions
argoproj-labs/terraform-provider-argocd pull request #522
Opened 2024-12-18 02:20 UTC by pouriyabp

This fix enhances the policy validation function to support the update and delete actions, in addition to the previously supported action keyword.

Per the documentation on [Fine-grained Permissions for update/delete actions](https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#fine-grained-permissions-for-updatedelete-action), the update and delete actions allow users to perform operations on an application and all of its resources. Additionally, these actions can be scoped to specific resources using the <action>/<group>/<kind>/<ns>/<name> format.

To align with this functionality, the regex used in policy validation has been updated to recognize update and delete as valid actions. This ensures that policies leveraging fine-grained permissions for update and delete are now properly validated.

2024-12-23 04:29 UTC, pouriyabp commented
[issue](https://github.com/argoproj-labs/terraform-provider-argocd/issues/524)

2025-03-12 21:01 UTC, mkilchhofer commented
Xref:
- https://github.com/argoproj/argo-cd/pull/19338

2025-03-12 21:06 UTC, mkilchhofer requested changes
Hi @pouriyabp sorry for the late response. Only a small finding, then I think we are good.

2025-03-12 21:06 UTC, mkilchhofer commented on argocd/utils.go
> +		regexp.MustCompile("(action|update|delete)/.*"),
Can we use the form which is available in upstream Argo CD?
```suggestion
		regexp.MustCompile("action/.*"),
		regexp.MustCompile("update/.*"),
		regexp.MustCompile("delete/.*"),
```

See PR https://github.com/argoproj/argo-cd/pull/19338/files

<img width="1266" alt="grafik" src="https://github.com/user-attachments/assets/1235594b-a705-46e5-87ad-d9f60884419e" />

2025-03-12 21:25 UTC, pouriyabp commented on argocd/utils.go
> +		regexp.MustCompile("(action|update|delete)/.*"),
Hi @mkilchhofer, no problem at all, and thanks for the review!

2025-03-12 22:17 UTC, mkilchhofer commented
@the-technat @onematchfox do we need a conditional with a new feature toggle/gate as these two new regexes are only valid in Argo CD 2.12+?

I assume that Argo CD <2.12 will decline the creation of projects with these regexes and thus the provider will throw the error to the user?

2025-03-13 06:14 UTC, mkilchhofer commented
@pouriyabp I added a test for you so our CI will validate your enhancement of the regexes.

2025-03-13 07:38 UTC, the-technat commented
Maybe we can add a version validation here: https://github.com/argoproj-labs/terraform-provider-argocd/blob/main/internal/features/features.go

Other features already use this to check if it's supported, just not sure how difficult it is to implement for a regex extension.

2025-03-13 07:38 UTC, the-technat commented
Maybe we can add a version validation here: https://github.com/argoproj-labs/terraform-provider-argocd/blob/main/internal/features/features.go

Other features already use this to check if it's supported, just not sure how difficult it is to implement for a regex extension.

2025-03-13 13:45 UTC, mkilchhofer commented
> Maybe we can add a version validation here: https://github.com/argoproj-labs/terraform-provider-argocd/blob/main/internal/features/features.go
> 
> Other features already use this to check if it's supported, just not sure how difficult it is to implement for a regex extension.

I added the feature conditional on the test only:
![image](https://github.com/user-attachments/assets/534eaf2f-52de-4b0e-b26b-d2d6b2170a3d)
![image](https://github.com/user-attachments/assets/566c8e02-0446-430c-8d1a-a7652b01933d)

And to check it already on the regex, we need to pass the Argo server version down to utils. Do we want that, @the-technat?

2025-03-13 13:45 UTC, the-technat approved these changes

2025-03-13 13:51 UTC, mkilchhofer approved these changes

2025-03-13 13:52 UTC, merged